### ISSUE TITLE
chess.com api redirects non-lowercase usernames to lowercase usernames

### ISSUE THREAD

**Issue by danieleff** [orieuxe/pogchamps#1]
For example 

https://api.chess.com/pub/player/BobbyHall/stats redirects to https://api.chess.com/pub/player/bobbyhall/stats

Which means that the pogchamps participants page currently starts with 9 unnecessary network requests. 

Even if cached, they could be skipped.

**Comment by orieuxe** [comment]
Thank you for noticing ! Btw, this was my first ever issue solved on github thanks to you 😄
