### ISSUE TITLE
Pogchamps 1 Participants page not loading

### ISSUE THREAD

**Issue by runningpersona** [orieuxe/pogchamps#2]
https://www.pogchampschess.com/participants when set to pogchamps 1 does load any players data since it cannot resolve Voyboy's stats. 

It looks for his old account called "VoyboyGENIUS" instead of his newly renamed one "Voyboy".

The page is permanently stuck like this:
https://i.imgur.com/BjOF3mE.png

Shows that the error is related to voyboygenius not existing.
https://i.imgur.com/sYSDTZp.png

**Comment by orieuxe** [comment]
thank you for noticing 👍 I just changed Voyboy's username in the database, hence  no commits required.
