### ISSUE TITLE
Match time doesnt update

### ISSUE THREAD

**Issue by Wooster8800** [orieuxe/pogchamps#3]
There's a bug in the match time not updating when toggling between championship and cons brackets.

**Comment by orieuxe** [comment]
thank you for noticing 👍  This should be fixed now.

**Comment by Wooster8800** [comment]
seems like its persisting.

**Comment by orieuxe** [comment]
Try refresh the page, it works as expected from what i can see. It takes time to re-build the application on client-side sometimes

**Comment by Wooster8800** [comment]
Cleared my cache and it works!  Nice response time!
